ETicket/Models/Movie.cs
using ETicket.Data.Base;
using ETicket.Data.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ETicket.Models
{
    public class Movie:IEntityBase
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string ImageUrl { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public MovieCategory MovieCategory { get; set; }
        public List<Actor_Movie> Actors_Movies { get; set; }
        public int CinemaId { get; set; }
        [ForeignKey("CinemaId")]
        public Cinema Cinema { get; set; }

        public int ProducerId { get; set; }
        [ForeignKey("ProducerId")]
        public Producer Producer { get; set; }
    }
}

ETicket/Controllers/ActorController.cs
using ETicket.Data;
using ETicket.Data.Services;
using ETicket.Data.Static;
using ETicket.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ETicket.Controllers
{
    [Authorize(Roles =UserRoles.Admin)]
    public class ActorController : Controller
    {
       
        private readonly IActorService db;
        public ActorController(IActorService _db)
        {
            db = _db;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var d=await db.GetAll();
            return View(d);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureUrl,Bio")]Actor actor)
        {
            await db.Add(actor);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(int Id)
        {
            var a = await db.GetById(Id);
            if (a == null)
                return View("NotFound");
            return View(a);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int Id,[Bind("Id,FullName,ProfilePictureUrl,Bio")] Actor actor)
        {
            await db.Update(Id,actor);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var a = await db.GetById(Id);
            
            return View(a);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            await  db.Delete(Id);
        

            return RedirectToAction(nameof(Index));
        }
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var d =await db.GetById(id);
            if (d == null)
                return View("NotFound");
            return View(d); 
        }
    }
}

ETicket/Controllers/CinemaController.cs
using ETicket.Data;
using ETicket.Data.Services;
using ETicket.Data.Static;
using ETicket.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ETicket.Controllers
{
    [Authorize(Roles =UserRoles.Admin)]
    public class CinemaController : Controller
    {
        private readonly ICinemaService db;
        public CinemaController(ICinemaService _db)
        {
            db = _db;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var d= await db.GetAll();   
            return View(d);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description")]Cinema c)
        { 
            await db.Add(c);
            return RedirectToAction("Index");
        }
        [AllowAnonymous]
        public async Task<IActionResult> Details(int Id)
        {
            var d = await db.GetById(Id);
            if (d == null)
                return View("NotFound");
            return View(d);
        }
        public async Task<IActionResult> Update(int id)
        {
            var d=await db.GetById(id);
            if (d == null)
                return View("NotFound");
            return View(d);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id,[Bind("Id,Logo,Name,Description")]Cinema c)
        {
            await db.Update(id,c);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int Id)
        {
            var a = await db.GetById(Id);

            return View(a);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            await db.Delete(Id);


            return RedirectToAction(nameof(Index));
        }

    }
}

ETicket/Controllers/MovieController.cs
using ETicket.Data;
using ETicket.Data.Services;
using ETicket.Data.Static;
using ETicket.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ETicket.Controllers
{
    [Authorize(Roles =UserRoles.Admin)]
    public class MovieController : Controller
    {
        private readonly IMovieService db;
        public MovieController(IMovieService _db)
        {
            db = _db;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var d=await  db.GetAllAsync(n => n.Cinema);
            return View(d);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var d = await db.GetAllAsync(n => n.Cinema);
            if(!string.IsNullOrEmpty(searchString))
                {
               var resu = d.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) || n.Description.ToLower().Contains(searchString.ToLower())).ToList();
                return View("Index", resu);
            }
            return View("Index",d);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var m = await db.GetMovieById(id);
            return View(m);
        }
        public async Task<IActionResult> Create() 
        {
            var dd = await db.GetNewMovieDropdown();
            ViewBag.CinemaId = new SelectList(dd.Cinemas, "Id", "Name");
            ViewBag.ProducerId = new SelectList(dd.Producers, "Id", "FullName");
            ViewBag.ActorId = new SelectList(dd.Actors, "Id", "FullName");

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(NewMovieVm v)
        {
            await db.AddNewMovie(v);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int Id)
        {
            var mm=await db.GetMovieById(Id);
            if (mm == null)
                return View("NotFound");
            var response = new NewMovieVm()
            {
                Id = mm.Id,
                Name = mm.Name,
                Description = mm.Description,
                Price = mm.Price,
                ImageUrl = mm.ImageUrl,
                MovieCategory = mm.MovieCategory,
                CinemaId = mm.CinemaId,
                ProducerId = mm.ProducerId,
                ActorIds = mm.Actors_Movies.Select(n => n.ActorId).ToList()
            };
            var dd = await db.GetNewMovieDropdown();
            ViewBag.CinemaId = new SelectList(dd.Cinemas, "Id", "Name");
            ViewBag.ProducerId = new SelectList(dd.Producers, "Id", "FullName");
            ViewBag.ActorId = new SelectList(dd.Actors, "Id", "FullName");

            return View(response);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id,NewMovieVm v)
        {
            if (id != v.Id)
                return View("NotFound");
            await db.UpdateMovie(v);
            return RedirectToAction("Index");
        }


    }
}

ETicket/Controllers/OrdersController.cs
using ETicket.Data.Cart;
using ETicket.Data.Services;
using ETicket.Data.Static;
using ETicket.Data.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ETicket.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IMovieService movieService;
        private readonly ShoppingCart shoppingCart;
        private readonly IOrdersService ordersService;
        public OrdersController(IMovieService _movieService,ShoppingCart _shoppingCart, IOrdersService _ordersService) 
        {
            movieService = _movieService;
            shoppingCart = _shoppingCart;
            ordersService = _ordersService;
        }
        public async Task<IActionResult> GetWhatOrdered()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders =await ordersService.GetOrdersByUserId(userId,userRole);
            return View(orders);
        }
        public IActionResult Index()
        {
            var it=shoppingCart.GetShoppingCartItems();
            shoppingCart.ShoppingCartItems=it;
            var response = new ShoppingCartVM()
            {
                ShoppingCart = shoppingCart,
                ShoppingCartTotal = shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }
        public async Task<RedirectToActionResult> AddToShoppingCart(int  id) 
        {
            var i =await movieService.GetMovieById(id);     
            if(i!=null)
            {
                shoppingCart.AddItemCart(i);
            }
            return RedirectToAction(nameof(Index));
        }
        public async Task<RedirectToActionResult> RemoveItemFromShoppingCart(int id)
        {
            var i = await movieService.GetMovieById(id);
            if (i != null)
            {
                shoppingCart.RemoveItemFromCart(i);
            }
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> CompleteOrder()
        {
            var items = shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);
            await ordersService.StoreOrder(items, userId, userEmailAddress);
            await shoppingCart.ClearShoppingCart();
            return View("OrderCompleted");
        }
    }
}
                   

ETicket/Controllers/ProducerController.cs
using ETicket.Data;
using ETicket.Data.Services;
using ETicket.Data.Static;
using ETicket.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ETicket.Controllers
{
    [Authorize(Roles =UserRoles.Admin)]
    public class ProducerController : Controller
    {
        private readonly IProducerService db;
        public ProducerController(IProducerService _db)
        {
            db = _db;            
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var d = await db.GetAll(); ;
            return View(d);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Details(int Id)
        {
            var d= await db.GetById(Id);
            if (d == null)
                return View("NotFound");
            return View(d);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfilePictureUrl,FullName,Bio")]Producer p)
        {   
            await db.Add(p);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Update(int Id)
        {
            var d = await db.GetById(Id);
            if (d == null)
                return View("NotFound");
            return View(d);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int Id,[Bind("Id,ProfilePictureUrl,FullName,Bio")] Producer p)
        {
            if (Id == p.Id)
            {
                await db.Update(Id, p);
                return RedirectToAction(nameof(Index));
            }
            return View(p);
        }
        public async Task<IActionResult> Delete(int Id)
        {
            var a = await db.GetById(Id);
            if (a == null)
                return View("NotFound");

            return View(a);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            await db.Delete(Id);
            return RedirectToAction(nameof(Index));
        }

    }
}

ETicket/Views/Movie/Create.cshtml
@model NewMovieVm
@using ETicket.Data.Enums;
@{
    ViewData["Titel"] = "Create a new Movie";
}
<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new Movie</h4>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-controller="Movie" asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-asp-validation-for="Name" class="text-daner"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-daner"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-daner"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-daner"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageUrl" class="control-label"></label>
                                <input asp-for="ImageUrl" class="form-control" />
                                <span asp-validation-for="ImageUrl" class="text-daner"></span>
                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="CinemaId" class="control-label"></label>
                                <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.CinemaId" ></select>
                                <span asp-validation-for="CinemaId" class="text-daner"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MovieCategory" class="control-label"></label>
                                <select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()"></select>
                                <span asp-validation-for="MovieCategory" class="text-daner"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProducerId" class="control-label"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.ProducerId"></select>
                                <span asp-validation-for="ProducerId" class="text-daner"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ActorIds" class="control-label"></label>
                                <select asp-for="ActorIds" class="form-control" multiple asp-items="ViewBag.ActorId"></select>
                                <span asp-validation-for="ActorIds" class="text-daner"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-daner"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-controller="Movie" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $("#ImageUrl").on("change",function(){
            var output=document.getElementById("ImageUrlPreview");
            output.src=$(this).val();
        })
    </script>
}

ETicket/Views/Movie/Details.cshtml
@model Movie

@{
    ViewData["Title"] = "Movie details";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageUrl" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Cinema: </b>
                            <a asp-controller="Cinema" asp-action="Details" asp-route-id="@Model.CinemaId">
                                @Model.Cinema.Name
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Producer: </b>
                            <a asp-controller="Producer" asp-action="Details" asp-route-id="@Model.ProducerId">
                                @Model.Producer.FullName
                            </a>
                        </p>
                        <p class="card-text"><b>Category: </b>@Model.MovieCategory</p>
                        <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">EXPIRED</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>
                            }
                        </p>
                        <p class="card-text">
                            <b>Actors: </b>
                            <hr />
                            <div class="row">
                                @foreach (var actor in Model.Actors_Movies)
                                {
                                    <div class="column text-center">
                                        <img class="border-info rounded-circle" src="@actor.Actor.ProfilePictureUrl" style="max-width: 150px" />
                                        <br />
                                        <a asp-controller="Actor" asp-action="Details" asp-route-id="@actor.ActorId">@actor.Actor.FullName</a>
                                    </div>
                                }
                            </div>
                        </p>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                            <a class="btn btn-success text-white @((DateTime.Now > Model.EndDate) ? "disabled": "")" asp-controller="Orders" asp-action="AddToShoppingCart" asp-route-id="@Model.Id"><i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ETicket/Views/Movie/Edit.cshtml
@model NewMovieVm
@using ETicket.Data.Enums;
@{
    ViewData["Title"] = "Update Movie";
}
<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new Movie</h4>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-controller="Movie" asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-daner"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageUrl" class="control-label"></label>
                                <input asp-for="ImageUrl" class="form-control" />
                                <span asp-validation-for="ImageUrl" class="text-danger"></span>
                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="CinemaId" class="control-label"></label>
                                <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.CinemaId" ></select>
                                <span asp-validation-for="CinemaId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MovieCategory" class="control-label"></label>
                                <select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()"></select>
                                <span asp-validation-for="MovieCategory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProducerId" class="control-label"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.ProducerId"></select>
                                <span asp-validation-for="ProducerId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ActorIds" class="control-label"></label>
                                <select asp-for="ActorIds" class="form-control" multiple asp-items="ViewBag.ActorId"></select>
                                <span asp-validation-for="ActorIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-daner"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-controller="Movie" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function(){
            var output=document.getElementById("ImageUrlPreview");
            output.src = $("#ImageUrl").val();
        });
        $("#ImageUrl").on("change",function(){
            var output=document.getElementById("ImageUrlPreview");
            output.src=$(this).val();
        })
    </script>
}

ETicket/Views/Movie/Index.cshtml
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "list of Movies";
}
<div class="row">
    @foreach(var v in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="cpl-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-next">
                                <h5 class="card-title">
                                    @v.Name
                                    @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                <a class="text-white float-right" asp-controller="Movie" asp-action="Edit" asp-route-Id="@v.Id"><i class="bg-info bi-pencil-square"></i></a>

                                }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@v.ImageUrl" width="100%" alt="@v.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@v.Description</p>
                            <p class="card-text"><b>Cinema: </b>@v.Cinema.Name</p>
                            <p class="card-text"><b>Category: </b>@v.MovieCategory</p>
                            <p class="card-text"><b>Start Date: </b>@v.StartDate.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>End Date: </b>@v.EndDate.ToString("dd MMM yy")</p>
                            <p class="card-text">
                                <b>Status: </b>
                                @if(DateTime.Now>=v.StartDate && DateTime.Now <=v.EndDate)
                                {
                                    <span class="badge bg-success text-white">Available</span>
                                }
                                else if(DateTime.Now > v.EndDate)
                                {
                                    <span class="badge bg-danger text-white">Expired</span>

                                }
                                else 
                                {
                                    <span class="badge bg-primary text-white">Upcoming</span>
                                }
                            </p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-controller="Movie" asp-action="Details" asp-route-Id="@v.Id"><i class="bi bi-eye-fill"></i>Show Details</a>
                                <a class="btn btn-success text-white @((DateTime.Now > v.EndDate) ? "disabled": "")" asp-controller="Orders" asp-action="AddToShoppingCart" asp-route-id="@v.Id"><i class="bi bi-cart-plus-"></i>Add to Cart(Price= Rs. @v.Price)</a>

                            </p>
                        </div>
                    </div>
                </div>

             </div>
         </div>
    }
</div>
@await Html.PartialAsync("_CreateItem","Movie")